### ISSUE TITLE
Any chance for adding video to the widget?

### ISSUE THREAD

**Issue by viraladmin** [papyrs/stylo#76]
This is an amazing plugin, but it lacks the one important aspect of article writing - attaching videos. Seems to have all other features one would need.

Is this something being considered? 

Doesn't need to be elaborate. Add link to youtube, options to resize similar to that of resizing images. Done.

**Comment by peterpeterparker** [comment]
Thanks for the question. I do not have to plan to provide more default plugins - widgets than those already existing. I rather like to focus on the core of the editor.

That's why Stylo is modular. You can develop your own widget to attach videos as described in the chapter [Plugins](https://github.com/papyrs/stylo#plugins) of the README.
