### ISSUE TITLE
Doesn't work with CDN 

### ISSUE THREAD

**Issue by faizananwerali** [papyrs/stylo#94]
### Expected Behavior

Should work with CDN

### Actual Behavior

Doesn't work with CDN 

### Reproduction

Steps to reproduce the issue:

1. check here https://codepen.io/faizanrupani/pen/ExQeQLp

### Environment

- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by peterpeterparker** [comment]
It doesn't work in the sample you provided because not all the required steps are set. In addition to fetching the lib it needs to be configured as displayed in [usage](https://github.com/papyrs/stylo#usage) chapter of the README.

You can also check how I do it in the [website](https://github.com/papyrs/stylo/blob/d25c4c40608b6b41a4d5f9a02ad4f6b68595c580/src/index.html#L667).

If it still does not work out please let me know, happy to reopen the question / issue if that would be the case.
